GET http://localhost:3003/api/blogs/

###
POST http://localhost:3003/api/blogs/ HTTP/1.1
content-type: application/json

{
  "title": "Mushrooms Kingdom",
  "author": "Princess Peach",
  "url": "test.2",
  "likes": 333
}
